export const AUTHORIZATION = 'Authorization'
export const BEARER = 'Bearer'
export const SET_COOKIE = 'Set-Cookie'
export const COOKIE_DEFAULT_SETTINGS = 'HttpOnly; SameSite=Strict; Secure;'
export const ACCESS_CONTROL_ALLOW_ORIGIN = 'Access-Control-Allow-Origin'
export const ACCESS_CONTROL_EXPOSE_HEADERS = 'Access-Control-Expose-Headers'
