export const AUTHORIZATION = 'authorization'
export const BEARER = 'Bearer'
export const ACCESS_CONTROL_EXPOSE_HEADERS = 'Access-Control-Expose-Headers'
export const USER_AGENT = 'user-agent'
export const UNKNOWN = 'unknown'