fragment UserFragment on User {
  _id
  transfercode
  name
  email
  newsletter
  cards {
    creationDate
    stamps {
      creationDate
    }
  }
  createdAt
  updatedAt
}

query getUsers {
  getUsers {
    ...UserFragment
  }
}

query getCurrentUser {
  getCurrentUser {
    ...UserFragment
  }
}

mutation updateUser(
  $_id: ID!
  $name: String
  $email: String
  $newsletter: Boolean!
  $password: String
) {
  updateUser(
    _id: $_id
    name: $name
    email: $email
    newsletter: $newsletter
    password: $password
  ) {
    ...UserFragment
  }
}

mutation signUp(
  $name: String
  $email: String
  $newsletter: Boolean!
  $password: String
) {
  signUp(
    name: $name
    email: $email
    newsletter: $newsletter
    password: $password
  )
}

mutation signIn($transfercode: String!, $password: String) {
  signIn(transfercode: $transfercode, password: $password)
}

mutation signOut {
  signOut
}

mutation refresh {
  refresh
}
