fragment UserFragment on User {
  _id
  transfercode
  name
  email
  newsletter
  cards {
    creationDate
    stamps {
      creationDate
    }
  }
  createdAt
  updatedAt
}

fragment RefreshTokenFragment on RefreshToken {
  _id
  user {
    _id
  }
  expires
  created
  createdByIp
  createdByUserAgent
  createdAt
  updatedAt
}

query getUsers {
  getUsers {
    ...UserFragment
  }
}

query getCurrentUser {
  getCurrentUser {
    ...UserFragment
  }
}

query getActiveRefreshTokens {
  getActiveRefreshTokens {
    ...RefreshTokenFragment
  }
}

mutation updateUser(
  $_id: ID!
  $name: String
  $email: String
  $newsletter: Boolean!
  $password: String
) {
  updateUser(
    _id: $_id
    name: $name
    email: $email
    newsletter: $newsletter
    password: $password
  ) {
    ...UserFragment
  }
}

mutation signUp(
  $name: String
  $email: String
  $newsletter: Boolean!
  $password: String
  $successRedirect: String!
) {
  signUp(
    name: $name
    email: $email
    newsletter: $newsletter
    password: $password
    successRedirect: $successRedirect
  )
}

mutation signIn($transfercode: String!, $password: String, $successRedirect: String!) {
  signIn(transfercode: $transfercode, password: $password, successRedirect: $successRedirect)
}

mutation signOut {
  signOut
}

mutation refresh {
  refresh
}

mutation revokeRefreshToken($_id: ID!) {
  revokeRefreshToken(_id: $_id)
}